### ISSUE TITLE
Coins and bills asset

### ISSUE THREAD

**Issue by Xynking** [bulletproofpancake/GAMEPROJ2#7]
1 peso coin
5 peso coin
10 peso coin

20 peso bill
50 peso bill
100 peso bill
500 peso bill'
1000 peso bill

**Comment by bulletproofpancake** [comment]
Bills are implemented

**Comment by bulletproofpancake** [comment]
implemented at d37d0e1474c117a6ab7327ffa1348aad4eac5c55
